- name: Install httpd
  hosts: dev
  become: yes
  tasks:
    - name: ensure httpd is installed
      yum:
        name: httpd
        state: installed
    - name: start httpd service
      service:
        name: httpd
        state: started

   
  
